# Generated by Django 3.2.5 on 2021-08-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_Season_Stat',
            new_name='Team_Season_Stats',
        ),
    ]
