# Generated by Django 3.2.5 on 2021-08-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_team_season_stat_team_season_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_Season_Stats',
            new_name='TeamSeasonStats',
        ),
    ]
