# Generated by Django 3.2.5 on 2021-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonstats',
            name='team_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
