# Generated by Django 3.2.5 on 2021-08-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season_stats', '0002_auto_20210806_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='auth.user'),
            preserve_default=False,
        ),
    ]
